[package]
name = "camera"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
absolute_unit.workspace = true
bevy.workspace = true
# internal
geodesy.workspace = true