[package]
name = "terrain"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
approx.workspace = true
bevy.workspace = true
bv.workspace = true
clap.workspace = true
glam.workspace = true
ordered-float.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true
# libs
absolute_unit.workspace = true
geodesy.workspace = true
geometry.workspace = true
